ALPHA: '0.97'
C3: '0.5'
FUNCTION: x[0]*x[1]
MAX_ITERATION: '10'
MAX_T: '100'
MAX_X: '5.12'
MIN_MASS: '0.01'
MIN_T: '0.1'
MIN_X: '-5.12'
PARTICLE_COUNT: '10'
USE_ANNEALING: false
USE_EXTINCTION: false
USE_INERTION: false
USE_NEIGHBOURS: false
W: '0.729'
